project:
  type: website
  output-dir: _site

website:
  title: "LIAC"
  navbar:
    left:
      - team.qmd
      - research.qmd
      - news.qmd
      - openings.qmd
      - text: Teaching
        menu:
        - text: AI for Chemistry
          href: https://schwallergroup.github.io/ai4chem_course/
      - text: EPFL
        menu:
        - text: Institute of Chemical Sciences and Engineering – ISIC
          href: https://www.epfl.ch/schools/sb/research/isic/
        - text: Laboratory of Artificial Chemical Intelligence - LIAC
          href: https://www.epfl.ch/labs/liac/
    right:
      - icon: github
        href: https://github.com/schwallergroup
      - icon: twitter
        href: https://twitter.com/SchwallerGroup
  google-analytics: "G-HNV4RSCCZX"
  twitter-card:
    creator: "@pschwllr"
    site: "@SchwallerGroup"
    image: images/overview.jpg
    title: LIAC (Schwaller Group) at EPFL
    description: Laboratory of Artificial Chemical Intelligence at EPFL | AI-accelerated discovery and synthesis
format:
  html:
    theme: quartz
    css: styles.css