---
title: "Research"
---
<script type='text/javascript' src='https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js'></script>

A full list is available from the following <a href="https://scholar.google.com/citations?user=Tz0I4ywAAAAJ&hl=en&oi=ao">Google Scholar</a> profile.

## Journal articles, workshop papers, and preprints
<ol reversed>
<li><strong>J Guo, P Schwaller</strong>. <a rel="noreferrer noopener" href="https://doi.org/10.26434/chemrxiv-2023-qmqmq-v3" data-type="URL" data-id="https://doi.org/10.26434/chemrxiv-2023-qmqmq-v3" target="_blank">Augmented Memory: Capitalizing on Experience Replay to Accelerate De Novo Molecular Design</a>. <em>10.26434/chemrxiv-2023-qmqmq-v3</em>, 2023.<div data-badge-type="2" data-doi="10.26434/chemrxiv-2023-qmqmq-v3" data-condensed="true" data-hide-no-mentions="true" data-hide-less-than="10" class="altmetric-embed"></div></li>
<li><strong>AM Bran</strong>, S Cox, AD White, <strong>P Schwaller</strong>. <a rel="noreferrer noopener" href="https://arxiv.org/abs/2304.05376" data-type="URL" data-id="https://arxiv.org/abs/2304.05376" target="_blank">ChemCrow: Augmenting large-language models with chemistry tools</a>. <em>arXiv:2304.05376</em>, 2023.</li>
<li>KM Jablonka, <strong>P Schwaller</strong>, A Ortega-Guerrero, B Smit. <a rel="noreferrer noopener" href="http://dx.doi.org/10.26434/chemrxiv-2023-fw8n4" data-type="URL" data-id="http://dx.doi.org/10.26434/chemrxiv-2023-fw8n4" target="_blank">Is GPT-3 all you need for low-data discovery in chemistry?</a>. <em>10.26434/chemrxiv-2023-fw8n4</em>, 2023.<div data-badge-type="2" data-doi="10.26434/chemrxiv-2023-fw8n4" data-condensed="true" data-hide-no-mentions="true" data-hide-less-than="10" class="altmetric-embed"></div></li>
<li><strong>J Guo, B Ranković, P Schwaller</strong>*. <a rel="noreferrer noopener" href="http://dx.doi.org/10.2533/chimia.2023.31" data-type="URL" data-id="http://dx.doi.org/10.2533/chimia.2023.31" target="_blank">Bayesian Optimization for Chemical Reactions</a>. <em>Chimia</em>, 2023, 77, 31-31.</li>
<li><strong>B Ranković</strong>, RR Griffiths, HB Moss, <strong>P Schwaller</strong>*. <a rel="noreferrer noopener" href="http://dx.doi.org/10.26434/chemrxiv-2022-nll2j" data-type="URL" data-id="http://dx.doi.org/10.26434/chemrxiv-2022-nll2j" target="_blank">Bayesian optimisation for additive screening and yield improvements in chemical reactions–beyond one-hot encodings</a>. <em>10.26434/chemrxiv-2022-nll2j</em>, 2022.<div data-badge-type="2" data-doi="10.26434/chemrxiv-2022-nll2j" data-condensed="true" data-hide-no-mentions="true" data-hide-less-than="10" class="altmetric-embed"></div></li>
<li>RR Griffiths, L Klarner, HB Moss, A Ravuri, S Truong, <strong>B Rankovic</strong>, Y Du, A Jamasb, J Schwartz, A Tripp, G Kell, A Bourached, A Chan, J Moss, C Guo, AA Lee, <strong>P Schwaller</strong>, J Tang. <a rel="noreferrer noopener" href="http://dx.doi.org/arXiv:2212.04450" data-type="URL" data-id="http://dx.doi.org/arXiv:2212.04450" target="_blank">GAUCHE: A Library for Gaussian Processes in Chemistry</a>. <em>arXiv:2212.04450</em>, 2022.</li>
<li> <strong>AM Bran, P Schwaller</strong>. <a rel="noreferrer noopener" href="https://openreview.net/forum?id=8YEB51L_vwV" data-type="URL"  target="_blank">Differential top-k learning for template-based single-step retrosynthesis</a>. <em>AI for Accelerated Materials Design NeurIPS 2022 workshop</em>, 2022.
<li>S Barthel, M Krenn, Qi Ai, N Carson, A Frei, NC Frey, P Friederich, T Gaudin, AA Gayle, KM Jablonka, RF Lameiro, D Lemm, A Lo, SM Moosavi, JM Napoles-Duarte, AK Nigam, R Pollice, K Rajan, U Schatzschneider, <strong>P Schwaller</strong>, M Skreta, B Smit, F Strieth-Kalthoff, C Sun, G Tom, GF von Rudolf, A Wang, A White, A Young, R Yu, A Aspuru-Guzik. <a rel="noreferrer noopener" href="http://dx.doi.org/10.1016/j.patter.2022.100588" data-type="URL" data-id="http://dx.doi.org/10.1016/j.patter.2022.100588" target="_blank">SELFIES and the future of molecular string representations</a>. <em>Patterns</em>, 2022, 3, 10, 100588.<div data-badge-type="2" data-doi="10.1016/j.patter.2022.100588" data-condensed="true" data-hide-no-mentions="true" data-hide-less-than="10" class="altmetric-embed"></div></li>
</ol>

## Prior to EPFL

<ol reversed>
<li>A Toniato, AC Vaucher, <strong>P Schwaller</strong>, T Laino. <a rel="noreferrer noopener" href="http://dx.doi.org/10.1039/d2dd00110a" data-type="URL" data-id="http://dx.doi.org/10.1039/d2dd00110a" target="_blank">Enhancing diversity in language based models for single-step retrosynthesis</a>. <em>Digital Discovery</em>, 2023, Accepted manuscript.</li>
<li>D Probst, <strong>P Schwaller</strong>, JL Reymond. <a rel="noreferrer noopener" href="http://dx.doi.org/10.1039/d1dd00006c" data-type="URL" data-id="http://dx.doi.org/10.1039/d1dd00006c" target="_blank">Reaction classification and yield prediction using the differential reaction fingerprint DRFP</a>. <em>Digital Discovery</em>, 2022, 1, 91-97.<div data-badge-type="2" data-doi="10.1039/D1DD00006C" data-condensed="true" data-hide-no-mentions="true" data-hide-less-than="10" class="altmetric-embed"></div></li>
<li><strong>P Schwaller</strong>*, AC Vaucher, R Laplaza, C Bunne, A Krause, C Corminboeuf, and T Laino. <a rel="noreferrer noopener" href="http://dx.doi.org/10.1002/wcms.1604" data-type="URL" data-id="http://dx.doi.org/10.1002/wcms.1604" target="_blank">Machine intelligence for chemical reaction space</a>. <em>WIREs Comput. Mol. Sci.</em>, 2022, e1604.<div data-badge-type="2" data-doi="10.1002/wcms.1604" data-condensed="true" data-hide-no-mentions="true" data-hide-less-than="10" class="altmetric-embed"></div></li>
<li>A Thakkar, <strong>P Schwaller</strong>*. <a rel="noreferrer noopener" href="http://dx.doi.org/10.2533/chimia.2021.677" data-type="URL" data-id="http://dx.doi.org/10.2533/chimia.2021.677" target="_blank">How AI for Synthesis Can Help Tackle Challenges in Molecular Discovery</a>. <em>CHIMIA</em>, 2021, 75, 7-8, 677-678.</li>
<li>D Kreutter, <strong>P Schwaller</strong>, JL Reymond. <a rel="noreferrer noopener" href="http://dx.doi.org/10.1039/d1sc02362d" data-type="URL" data-id="http://dx.doi.org/10.1039/d1sc02362d" target="_blank">Predicting Enzymatic Reactions with a Molecular Transformer</a>. <em>Chem. Sci.</em>, 2021, 12, 8648-8659. <a rel="noreferrer noopener" href="https://pubs.rsc.org/en/content/articlepdf/2021/sc/d1sc90137k" data-type="URL" data-id="https://pubs.rsc.org/en/content/articlepdf/2021/sc/d1sc90137k" target="_blank">Chemical Science cover</a>. <a rel="noreferrer noopener" href="https://pubs.rsc.org/en/journals/articlecollectionlanding?sercode=sc&themeid=37bb1c56-65cf-4755-9be7-0308de537b6d" data-type="URL" data-id="https://pubs.rsc.org/en/journals/articlecollectionlanding?sercode=sc&themeid=37bb1c56-65cf-4755-9be7-0308de537b6d" target="_blank">Most popular 2021 physical and theoretical chemistry articles</a>.<div data-badge-type="2" data-doi="10.1039/D1SC02362D" data-condensed="true" data-hide-no-mentions="true" data-hide-less-than="10" class="altmetric-embed"></div></li>
<li>AC Vaucher, <strong>P Schwaller</strong>, J Geluykens, VH Nair, A Iuliano, T Laino. <a rel="noreferrer noopener" href="http://dx.doi.org/10.1038/s41467-021-22951-1" data-type="URL" data-id="http://dx.doi.org/10.1038/s41467-021-22951-1" target="_blank">Inferring experimental procedures from text-based representations of chemical reactions</a>. <em>Nature Comm.</em>, 2021, 12 (1), 1-11. <a rel="noreferrer noopener" href="https://www.nature.com/collections/gcijejjahe" data-type="URL" data-id="https://www.nature.com/collections/gcijejjahe" target="_blank"><strong>Editors' highlight</strong> in Computation and Machine Learning for Chemistry</a>. <a rel="noreferrer noopener" href="https://chemistrycommunity.nature.com/posts/predicting-experimental-steps-for-arbitrary-chemical-equations" data-type="URL" data-id="https://chemistrycommunity.nature.com/posts/predicting-experimental-steps-for-arbitrary-chemical-equations" target="_blank">[Blog]</a>. <a rel="noreferrer noopener" href="https://github.com/rxn4chemistry/smiles2actions" data-type="URL" data-id="https://github.com/rxn4chemistry/smiles2actions" target="_blank">[Code]</a>.<div data-badge-type="2" data-doi="10.1038/s41467-021-22951-1" data-condensed="true" data-hide-no-mentions="true" data-hide-less-than="10" class="altmetric-embed"></div></li>
<li><strong>P Schwaller</strong>*, B Hoover, JL Reymond, H Strobelt, T Laino. <a rel="noreferrer noopener" href="http://dx.doi.org/10.1126/sciadv.abe4166" data-type="URL" data-id="http://dx.doi.org/10.1126/sciadv.abe4166" target="_blank">Extraction of organic chemistry grammar from unsupervised learning of chemical reactions</a>. <em>Sci. Adv.</em>, 2021, 7, 15, abe416. Featured in  <a rel="noreferrer noopener" href="https://bdtechtalks.com/2020/08/31/ibm-roborxn-ai-robotics-chemical-research/" data-type="URL" data-id="https://bdtechtalks.com/2020/08/31/ibm-roborxn-ai-robotics-chemical-research/" target="_blank"><strong>TechTalks</strong></a>, <a rel="noreferrer noopener" href="https://cen.acs.org/acs-news/acs-meeting-news/Machine-learning-maps-atoms/99/web/2021/04" data-type="URL" data-id="https://cen.acs.org/acs-news/acs-meeting-news/Machine-learning-maps-atoms/99/web/2021/04" target="_blank"><strong>C&EN</strong></a>. <a rel="noreferrer noopener" href="https://github.com/rxn4chemistry/rxnmapper" data-type="URL" data-id="https://github.com/rxn4chemistry/rxnmapper" target="_blank">[Code]</a>.<div data-badge-type="2" data-doi="10.1126/sciadv.abe4166" data-condensed="true" data-hide-no-mentions="true" data-hide-less-than="10" class="altmetric-embed"></div></li>
<li><strong>P Schwaller</strong>*, AC Vaucher, T Laino, JL Reymond. <a rel="noreferrer noopener" href="http://dx.doi.org/10.1088/2632-2153/abc81d" data-type="URL" data-id="http://dx.doi.org/10.1088/2632-2153/abc81d" target="_blank">Prediction of Chemical Reaction Yields using Deep Learning</a>. <em>Mach. Learn.: Sci. Technol.</em>, 2021, 2, 015016. <strong>Invited article</strong> for "Machine Learning for Chemical Reactions" focus collection. <a rel="noreferrer noopener" href="https://rxn4chemistry.github.io/rxn_yields/" data-type="URL" data-id="https://rxn4chemistry.github.io/rxn_yields/" target="_blank">[Code]</a>.<div data-badge-type="2" data-doi="10.1088/2632-2153/abc81d" data-condensed="true" data-hide-no-mentions="true" data-hide-less-than="10" class="altmetric-embed"></div></li>
<li>A Toniato, <strong>P Schwaller</strong>, A Cardinale, J Geluykens, T Laino. <a rel="noreferrer noopener" href="http://dx.doi.org/10.1038/s42256-021-00319-w" data-type="URL" data-id="http://dx.doi.org/10.1038/s42256-021-00319-w" target="_blank">Unassisted Noise-Reduction of Chemical Reactions Data Sets</a>. <em>Nat. Mach. Int.</em>, 2021, 3, 485–494. <a rel="noreferrer noopener" href="https://github.com/rxn4chemistry/OpenNMT-py/tree/noise_reduction" data-type="URL" data-id="https://github.com/rxn4chemistry/OpenNMT-py/tree/noise_reduction" target="_blank">[Code]</a>.<div data-badge-type="2" data-doi="10.1038/s42256-021-00319-w" data-condensed="true" data-hide-no-mentions="true" data-hide-less-than="10" class="altmetric-embed"></div></li>
<li><strong>P Schwaller</strong>*, D Probst, AC Vaucher, VH Nair, D Kreutter, T Laino, JL Reymond. <a rel="noreferrer noopener" href="http://dx.doi.org/10.1038/s42256-020-00284-w" data-type="URL" data-id="http://dx.doi.org/10.1038/s42256-020-00284-w" target="_blank">Mapping the Space of Chemical Reactions using Attention-Based Neural Networks.</a> <em>Nat. Mach. Int.</em>, 2021, 3, 144–152. <a rel="noreferrer noopener" href="https://www.nature.com/articles/s42256-021-00299-x" data-type="URL" data-id="https://www.nature.com/articles/s42256-021-00299-x" target="_blank">[News & Views]</a>. <a rel="noreferrer noopener" href="https://www.nature.com/articles/s42256-021-00367-2" data-type="URL" data-id="https://www.nature.com/articles/s42256-021-00367-2" target="_blank">[Matters Arising]</a>. <a rel="noreferrer noopener" href="https://www.nature.com/collections/ijabjccjec" data-type="URL" data-id="https://www.nature.com/collections/ijabjccjec" target="_blank">Synthesis and enabling technologies collection</a>. Featured in  <a rel="noreferrer noopener" href="https://cen.acs.org/physical-chemistry/computational-chemistry/Mapping-reaction-space-machine-learning/99/i5" data-type="URL" data-id="https://cen.acs.org/physical-chemistry/computational-chemistry/Mapping-reaction-space-machine-learning/99/i5" target="_blank"><strong>C&EN</strong></a>. <a rel="noreferrer noopener" href="https://rxn4chemistry.github.io/rxnfp/" data-type="URL" data-id="https://rxn4chemistry.github.io/rxnfp/" target="_blank">[Code]</a>.<div data-badge-type="2" data-doi="10.1038/s42256-020-00284-w" data-condensed="true" data-hide-no-mentions="true" data-hide-less-than="10" class="altmetric-embed"></div></li>
<li>G Pesciullesi•, <strong>P Schwaller</strong>•, T Laino, JL Reymond. <a rel="noreferrer noopener" href="http://dx.doi.org/10.1038/s41467-020-18671-7" data-type="URL" data-id="http://dx.doi.org/10.1038/s41467-020-18671-7" target="_blank">Transfer learning enables the molecular transformer to predict regio- and stereoselective reactions on carbohydrates</a>. <em>Nature Comm.</em>, 2020, 11, 4874. <a rel="noreferrer noopener" href="https://www.nature.com/collections/wdzvyhgxft" data-type="URL" data-id="https://www.nature.com/collections/wdzvyhgxft" target="_blank"><strong>Editors' highlight</strong> in Organic Chemistry and Chemical Biology</a>. <a rel="noreferrer noopener" href="https://chemistrycommunity.nature.com/posts/transfer-learning-enables-the-molecular-transformer-to-predict-regio-and-stereoselective-reactions-on-carbohydrates" data-type="URL" data-id="https://chemistrycommunity.nature.com/posts/transfer-learning-enables-the-molecular-transformer-to-predict-regio-and-stereoselective-reactions-on-carbohydrates" target="_blank">[Blog]</a>. <a rel="noreferrer noopener" href="https://github.com/rxn4chemistry/OpenNMT-py/tree/carbohydrate_transformer" data-type="URL" data-id="https://github.com/rxn4chemistry/OpenNMT-py/tree/carbohydrate_transformer" target="_blank">[Code]</a>.<div data-badge-type="2" data-doi="10.1038/s41467-020-18671-7" data-condensed="true" data-hide-no-mentions="true" data-hide-less-than="10" class="altmetric-embed"></div></li>
<li>AC Vaucher, F Zipoli, J Geluykens, VH Nair, <strong>P Schwaller</strong>, T Laino. <a rel="noreferrer noopener" href="http://dx.doi.org/10.1038/s41467-020-17266-6" data-type="URL" data-id="http://dx.doi.org/10.1038/s41467-020-17266-6" target="_blank">Automated extraction of chemical synthesis actions from experimental procedures</a>. <em>Nature Comm.</em>, 2020, 11 (1), 2041-1723. <a rel="noreferrer noopener" href="https://www.nature.com/collections/gcijejjahe" data-type="URL" data-id="https://www.nature.com/collections/gcijejjahe" target="_blank"><strong>Editors' highlight</strong> in Computation and Machine Learning for Chemistry</a>. Featured in  <a rel="noreferrer noopener" href="https://cen.acs.org/business/informatics/IBM-debuts-chemical-synthesis-robot/98/i34" data-type="URL" data-id="https://cen.acs.org/business/informatics/IBM-debuts-chemical-synthesis-robot/98/i34" target="_blank"><strong>C&EN</strong></a>. <a rel="noreferrer noopener" href="https://chemistrycommunity.nature.com/posts/automated-extraction-of-chemical-synthesis-actions-from-experimental-procedures" data-type="URL" data-id="https://chemistrycommunity.nature.com/posts/automated-extraction-of-chemical-synthesis-actions-from-experimental-procedures" target="_blank">[Blog]</a>. <a rel="noreferrer noopener" href="https://github.com/rxn4chemistry/paragraph2actions" data-type="URL" data-id="https://github.com/rxn4chemistry/paragraph2actions" target="_blank">[Code]</a>.<div data-badge-type="2" data-doi="10.1038/s41467-020-17266-6" data-condensed="true" data-hide-no-mentions="true" data-hide-less-than="10" class="altmetric-embed"></div></li>
<li>H Öztürk, A Özgür, <strong>P Schwaller</strong>, T Laino, E Ozkirimli. <a rel="noreferrer noopener" href="http://dx.doi.org/10.1016/j.drudis.2020.01.020" data-type="URL" data-id="http://dx.doi.org/10.1016/j.drudis.2020.01.020" target="_blank">Exploring chemical space using natural language processing methodologies for drug discovery</a>. <em>Drug Discovery Today</em>, 2020, 25 (4), 689-705.<div data-badge-type="2" data-doi="10.1016/j.drudis.2020.01.020" data-condensed="true" data-hide-no-mentions="true" data-hide-less-than="10" class="altmetric-embed"></div></li>
<li><strong>P Schwaller</strong>*, R Petraglia, V Zullo, V H Nair, R A Haeuselmann, R Pisoni, C Bekas, A Iuliano, T Laino. <a rel="noreferrer noopener" href="http://dx.doi.org/10.1039/c9sc05704h" data-type="URL" data-id="http://dx.doi.org/10.1039/c9sc05704h" target="_blank">Predicting retrosynthetic pathways using a combined linguistic model and hyper-graph exploration strategy</a>. <em>Chem. Sci.</em>, 2020,11, 3316-3325. <a rel="noreferrer noopener" href="https://www.ibm.com/blogs/research/2019/10/ibm-brings-ai-retrosynthetic-analysis-to-the-cloud/" data-type="URL" data-id="https://www.ibm.com/blogs/research/2019/10/ibm-brings-ai-retrosynthetic-analysis-to-the-cloud/" target="_blank">[Blog]</a>.<div data-badge-type="2" data-doi="10.1039/c9sc05704h" data-condensed="true" data-hide-no-mentions="true" data-hide-less-than="10" class="altmetric-embed"></div></li>
<li>VH Nair, <strong>P Schwaller</strong>, T Laino. <a rel="noreferrer noopener" href="http://dx.doi.org/10.2533/chimia.2019.997" data-type="URL" data-id="http://dx.doi.org/10.2533/chimia.2019.997" target="_blank">Data-driven Chemical Reaction Prediction and Retrosynthesis.</a> <em>Chimia</em>, 2020, 73 (12), 997-1000. <strong>Invited article</strong> for special "Artificial Intelligence in Swiss Chemical Research" issue.</li>
<li><strong>P Schwaller</strong>*, T Laino, T Gaudin, P Bolgar, CA Hunter, C Bekas, AA Lee. <a rel="noreferrer noopener" href="http://dx.doi.org/10.1021/acscentsci.9b00576" data-type="URL" data-id="http://dx.doi.org/10.1021/acscentsci.9b00576" target="_blank">Molecular Transformer – A Model for Uncertainty-Calibrated Chemical Reaction Prediction.</a> <em>ACS Cent. Sci.</em> 2019, 5, 9, 1572–1583. <a rel="noreferrer noopener" href="https://pubs.acs.org/action/showMostReadArticles?topArticlesType=recent&journalCode=acscii" data-type="URL" data-id="https://pubs.acs.org/action/showMostReadArticles?topArticlesType=recent&journalCode=acscii" target="_blank">ACS Central Science Top-10 Most Read Articles in 2020</a>. Featured in  <a rel="noreferrer noopener" href="https://cen.acs.org/physical-chemistry/computational-chemistry/Teaching-computers-read-speak-chemistry/99/i5" data-type="URL" data-id="https://cen.acs.org/physical-chemistry/computational-chemistry/Teaching-computers-read-speak-chemistry/99/i5" target="_blank"><strong>C&EN</strong></a>, <a rel="noreferrer noopener" href="https://www.chemistryworld.com/news/language-based-softwares-accurate-predictions-translate-to-benefits-for-chemists/4010437.article" data-type="URL" data-id="https://www.chemistryworld.com/news/language-based-softwares-accurate-predictions-translate-to-benefits-for-chemists/4010437.article" target="_blank"><strong>Chemistry World</strong></a>. <a rel="noreferrer noopener" href="https://www.cam.ac.uk/research/news/ai-learns-the-language-of-chemistry-to-predict-how-to-make-medicines" data-type="URL" data-id="https://www.cam.ac.uk/research/news/ai-learns-the-language-of-chemistry-to-predict-how-to-make-medicines" target="_blank">[Blog]</a>. <a rel="noreferrer noopener" href="https://github.com/pschwllr/MolecularTransformer" data-type="URL" data-id="https://github.com/pschwllr/MolecularTransformer" target="_blank">[Code]</a>.<div data-badge-type="2" data-doi="10.1021/acscentsci.9b00576" data-condensed="true" data-hide-no-mentions="true" data-hide-less-than="10" class="altmetric-embed"></div></li>
<li><strong>P Schwaller</strong>•*, T Gaudin•, D Lanyi, C Bekas, T Laino. <a rel="noreferrer noopener" href="http://dx.doi.org/10.1039/c8sc02339e" data-type="URL" data-id="http://dx.doi.org/10.1039/c8sc02339e" target="_blank">Found in Translation: predicting outcomes of complex organic chemistry reactions using neural sequence-to-sequence models</a>. <em>Chem. Sci.</em>, 2018, 9, 6091-609. <a rel="noreferrer noopener" href="https://pubs.rsc.org/en/journals/articlecollectionlanding?sercode=sc&themeid=02ec2dec-e7e7-4d78-8411-7afb634a771a" data-type="URL" data-id="https://pubs.rsc.org/en/journals/articlecollectionlanding?sercode=sc&themeid=02ec2dec-e7e7-4d78-8411-7afb634a771a" target="_blank">Chemical Science: Most popular articles 2018-2019</a>. Featured in  <a rel="noreferrer noopener" href="https://www.chemistryworld.com/news/ai-translates-chemistry-to-predict-reaction-outcomes/3008397.article" data-type="URL" data-id="https://www.chemistryworld.com/news/ai-translates-chemistry-to-predict-reaction-outcomes/3008397.article" target="_blank"><strong>Chemistry World</strong></a>, <a rel="noreferrer noopener" href="https://spectrum.ieee.org/tech-talk/artificial-intelligence/machine-learning/artificial-intelligence-learns-chemical-reactions" data-type="URL" data-id="https://spectrum.ieee.org/tech-talk/artificial-intelligence/machine-learning/artificial-intelligence-learns-chemical-reactions" target="_blank"><strong>IEEE Spectrum</strong></a>, <a rel="noreferrer noopener" href="https://www.technologyreview.com/2017/12/04/105020/a-translation-algorithm-can-predict-the-language-of-a-chemical-reaction/" data-type="URL" data-id="https://www.technologyreview.com/2017/12/04/105020/a-translation-algorithm-can-predict-the-language-of-a-chemical-reaction/" target="_blank"><strong>MIT Technology Review</strong></a>, <a rel="noreferrer noopener" href="https://phys.org/news/2017-12-artificial-intelligence-chemical-reactions.html" data-type="URL" data-id="https://phys.org/news/2017-12-artificial-intelligence-chemical-reactions.html" target="_blank"><strong>phys.org</strong></a>. <a rel="noreferrer noopener" href="https://www.ibm.com/blogs/research/2018/08/neural-networks-organic-chemistry/" data-type="URL" data-id="https://www.ibm.com/blogs/research/2018/08/neural-networks-organic-chemistry/" target="_blank">[Blog]</a>.<div data-badge-type="2" data-doi="10.1039/C8SC02339E" data-condensed="true" data-hide-no-mentions="true" data-hide-less-than="10" class="altmetric-embed"></div></li>
<li>M Makha, <strong>P Schwaller</strong>, K Strassel, SB Anantharaman, F Nüesch, R Hany, J Heier. <a rel="noreferrer noopener" href="http://dx.doi.org/10.1080/14686996.2018.1509275" data-type="URL" data-id="http://dx.doi.org/10.1080/14686996.2018.1509275" target="_blank">Insights into photovoltaic properties of ternary organic solar cells from phase diagrams</a>. <em>Sci. Technol. Adv. Mater.</em>, 2018, 19, 1, 669–682.</li>
<li>N Mounet, M Gibertini, <strong>P Schwaller</strong>, D Campi, A Merkys, A Marrazzo, T Sohier, IE Castelli, A Cepellotti, G Pizzi, N Marzari. <a rel="noreferrer noopener" href="http://dx.doi.org/10.1038/s41565-017-0035-5" data-type="URL" data-id="http://dx.doi.org/10.1038/s41565-017-0035-5" target="_blank">Two-dimensional materials from high-throughput computational exfoliation of experimentally known compounds</a>. <em>Nature Nanotech.</em>, 2018, 13, 246–252. <a rel="noreferrer noopener" href="https://nccr-marvel.ch/news/awards/2018-01-hpc-max-prize-2017-awarded-to-nicolas-mounet-and-colleagues" data-type="URL" data-id="https://nccr-marvel.ch/news/awards/2018-01-hpc-max-prize-2017-awarded-to-nicolas-mounet-and-colleagues" target="_blank"><strong>HPC Max Prize 2017</strong></a>. <a rel="noreferrer noopener" href="https://www.nature.com/nnano/volumes/13/issues/3" data-type="URL" data-id="https://www.nature.com/nnano/volumes/13/issues/3" target="_blank"><strong>Nature Nanotechnology cover</strong></a>. <a rel="noreferrer noopener" href="https://www.nature.com/articles/s41565-017-0060-4" data-type="URL" data-id="https://www.nature.com/articles/s41565-017-0060-4" target="_blank">[News & Views]</a>. Featured in  <a rel="noreferrer noopener" href="https://arstechnica.com/science/2018/02/there-are-probably-hundreds-of-graphene-like-chemicals-weve-not-studied-yet/" data-type="URL" data-id="https://arstechnica.com/science/2018/02/there-are-probably-hundreds-of-graphene-like-chemicals-weve-not-studied-yet/" target="_blank"><strong>arstechnica</strong></a>, <a rel="noreferrer noopener" href="https://phys.org/news/2018-03-treasure-trove-nanotechnology-experts.html" data-type="URL" data-id="https://phys.org/news/2018-03-treasure-trove-nanotechnology-experts.html" target="_blank"><strong>phys.org</strong></a>. <a rel="noreferrer noopener" href="https://www.nature.com/articles/s41565-017-0060-4" data-type="URL" data-id="https://www.nature.com/articles/s41565-017-0060-4" target="_blank">[Blog]</a>. <a rel="noreferrer noopener" href="https://archive.materialscloud.org/record/2020.158" data-type="URL" data-id="https://archive.materialscloud.org/record/2020.158" target="_blank">[Code]</a>.<div data-badge-type="2" data-doi="10.1038/s41565-017-0035-5" data-condensed="true" data-hide-no-mentions="true" data-hide-less-than="10" class="altmetric-embed"></div></li>
</ol>
